print ('Content-type:text/html\r\n\r\n')
print ('<html>')
print ('<body>')
print ('<center><h2>Grafx_IT</h2>')
print ('<form action="/studentdetails2.py" method="get" target="_blan">')
print ('<table cellpadding="5" width="30%" bgcolor="gold" align="center" cellspacing="10">')
print ('<tr><td colspan=2> <center><font size=4><b>Student Details</b></font></center></td></tr>')
print ('<tr> <td>Enter Student ID</td> <td><input type=text name="stu_id"  size="30"></td> </tr>')
print ('<tr> <td>Enter Student Name</td><td><input type="text" name="stu_name"  size="30"></td> </tr>')
print ('<tr> <td>Address</td><td> <textarea rows = "5" cols = "30" name = "stu_address"></textarea></td> </tr>')
print ('<tr> <td>Course Name </td><td><input type="text" name="stu_course"  size="30"></td> </tr>')
print ('<tr> <td>Course Fee</td><td><input type="text" name="stu_fee" size="30"></td> </tr>')
print ('</table>')
print ('</br>')
print ('<input type="submit" value="Add" style="color:Green;" name="insert_button">')
print ('<input type="submit" value="Delete" style="color:Red;" name="delete_button"> ')
print ('<input type="submit" value="Search By ID" style="color:blue;" name="select_button">')
print ('<input type="submit" value="Retrive All Data" style="color:navyblue; name="display_button">')
print ('<input type="submit" value="Update" style="color:Green;" name="update_button">')
print ('</br></br>')
print('<input type="reset">')
print ('</form></center>')
print ('</body>')
print ('</html>')
